### ISSUE TITLE
Consider a template repository

### ISSUE THREAD

**Issue by michaelmior** [hschne/reveal.js-starter#1]
Would you consider making this a [template repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository)? This just adds a helpful "Use this template" button on GitHub which is similar to a fork, but with [a few differences](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template) from forks. (It's still possible to fork a template repository as usual.)

**Comment by hschne** [comment]
Great idea! Already done! :+1:

**Comment by michaelmior** [comment]
Thanks :)
