### ISSUE TITLE
Rather heavy on some old dependencies ...

### ISSUE THREAD

**Issue by pkese** [hschne/reveal.js-starter#7]
# bash <(wget -qO- https://raw.githubusercontent.com/hschne/reveal.js-starter/master/bootstrap.sh)

    Please specify a name for your presentation: test

    Cloning Reveal.js Starter repository...
    Installing dependencies...

    Presentation sucessfully set up in 'test'
    Run 'npm run serve' to open it in your browser.

    # npm run serve

    > serve
    > gulp dev

    sh: 1: gulp: not found

    # npm install

    npm ERR! code 1
    npm ERR! path /home/peter/work/slides/test/node_modules/node-sass
    npm ERR! command failed
    npm ERR! command sh -c node scripts/build.js
    npm ERR! Building: /usr/bin/node /home/peter/work/slides/test/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp verb cli [
    npm ERR! gyp verb cli   '/usr/bin/node',
    npm ERR! gyp verb cli   '/home/peter/work/slides/test/node_modules/node-gyp/bin/node-gyp.js',
    npm ERR! gyp verb cli   'rebuild',
    npm ERR! gyp verb cli   '--verbose',
    npm ERR! gyp verb cli   '--libsass_ext=',
    npm ERR! gyp verb cli   '--libsass_cflags=',
    npm ERR! gyp verb cli   '--libsass_ldflags=',
    npm ERR! gyp verb cli   '--libsass_library='
    npm ERR! gyp verb cli ]
    npm ERR! gyp info using node-gyp@3.8.0
    npm ERR! gyp info using node@16.1.0 | linux | x64
    npm ERR! gyp verb command rebuild []
    npm ERR! gyp verb command clean []
    npm ERR! gyp verb clean removing "build" directory
    npm ERR! gyp verb command configure []
    npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
    npm ERR! gyp verb `which` failed Error: not found: python2
    npm ERR! gyp verb `which` failed     at getNotFoundError (/home/peter/work/slides/test/node_modules/which/which.js:13:12)
    npm ERR! gyp verb `which` failed     at F (/home/peter/work/slides/test/node_modules/which/which.js:68:19)
    npm ERR! gyp verb `which` failed     at E (/home/peter/work/slides/test/node_modules/which/which.js:80:29)
    npm ERR! gyp verb `which` failed     at /home/peter/work/slides/test/node_modules/which/which.js:89:16
    npm ERR! gyp verb `which` failed     at /home/peter/work/slides/test/node_modules/isexe/index.js:42:5
    npm ERR! gyp verb `which` failed     at /home/peter/work/slides/test/node_modules/isexe/mode.js:8:5
    npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:194:21)
    npm ERR! gyp verb `which` failed  python2 Error: not found: python2
    npm ERR! gyp verb `which` failed     at getNotFoundError (/home/peter/work/slides/test/node_modules/which/which.js:13:12)
    npm ERR! gyp verb `which` failed     at F (/home/peter/work/slides/test/node_modules/which/which.js:68:19)
    npm ERR! gyp verb `which` failed     at E (/home/peter/work/slides/test/node_modules/which/which.js:80:29)
    npm ERR! gyp verb `which` failed     at /home/peter/work/slides/test/node_modules/which/which.js:89:16
    npm ERR! gyp verb `which` failed     at /home/peter/work/slides/test/node_modules/isexe/index.js:42:5
    npm ERR! gyp verb `which` failed     at /home/peter/work/slides/test/node_modules/isexe/mode.js:8:5
    npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:194:21) {
    npm ERR! gyp verb `which` failed   code: 'ENOENT'
    npm ERR! gyp verb `which` failed }
    npm ERR! gyp verb check python checking for Python executable "python" in the PATH
    npm ERR! gyp verb `which` succeeded python /home/peter/bin/anaconda3/bin/python
    npm ERR! gyp ERR! configure error 
    npm ERR! gyp ERR! stack Error: Command failed: /home/peter/bin/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
    npm ERR! gyp ERR! stack   File "<string>", line 1
    npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
    npm ERR! gyp ERR! stack                       ^
    npm ERR! gyp ERR! stack SyntaxError: invalid syntax
    npm ERR! gyp ERR! stack 
    npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:326:12)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
    npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
    npm ERR! gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:453:11)
    npm ERR! gyp ERR! stack     at Socket.emit (node:events:365:28)
    npm ERR! gyp ERR! stack     at Pipe.<anonymous> (node:net:661:12)
    npm ERR! gyp ERR! System Linux 5.11.0-16-generic
    npm ERR! gyp ERR! command "/usr/bin/node" "/home/peter/work/slides/test/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
    npm ERR! gyp ERR! cwd /home/peter/work/slides/test/node_modules/node-sass
    npm ERR! gyp ERR! node -v v16.1.0
    npm ERR! gyp ERR! node-gyp -v v3.8.0
    npm ERR! gyp ERR! not ok 
    npm ERR! Build failed with error code: 1

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/peter/.npm/_logs/2021-05-16T16_58_35_248Z-debug.log

Gulp, python2, ... ?

All I wanted was to edit a slide deck. It wants me to time travel back into the 1990ties.

**Comment by hschne** [comment]
What do you have against the 90s :grin: 

I haven't updated this template in a while. I can update some of the old dependencies, but I don't have time to replace gulp at the moment. If you have any suggestions for how to improve this I'll gladly hear them :wink:

**Comment by pkese** [comment]
Sorry for the slightly cynical comment. I'm not familiar with the project but now on the second thought, I realize I should have given more respect to you and other folks investing your time and effort into free software.

My approach was primarily utilitarian. I was focused on finding a toll to get a job done and I ended up using `mdxp` that managed to `npm install` with less hassle (which doesn't imply that there weren't any).

As of suggestions, maybe getting rid of Python2 dependency would be a good start: most modern Linux distributions nowadays arrive with Python3 installed. I may be biased, but I prefer to avoid installing too many software packages on my machine, especially in this case, where Python3 is already installed and I haven't had a need for anything Python2 in years.

I don't mind Gulp, if that's what gets the job done - as long as it arrives with the install script (or npm install).

Thank you for your effort.

**Comment by hschne** [comment]
@pkese You may be interested to hear that I finally got around to updating this repository. I ditched Gulp and changed everything to use Rollup instead, which should alleviate the issues you faced. Functionality and everything should still be the same. 

I'd be super happy if you'd give this another try :)
